(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



data={};
Monitor[
Table[
	start=RandomInteger[1,{8,8}];
	largestcomp = EvolveLargestCluster[start,4,3,2000];
	
	comp = ComponentMeasurements[largestcomp, "Count",All,"PropertyAssociation"];
	max = Max[comp["Count"]];
	If[max>8,AppendTo[data,{start,max}];];
,{jj,1,1000}],jj];
data


data={};

Table[
	start=RandomInteger[1,{8,8}];
	predata = CellularAutomaton[<|\!\(\*
StyleBox[\"\\\"\"]\)OuterTotalisticCode"->224,"Dimension"->2,"Neighborhood"->9|>,{start,0},{{4000,4008}}];
	If[predata[[1]]!= {},
	morph=MorphologicalComponents[predata];
	comp = ComponentMeasurements[morph, "Count",All,"PropertyAssociation"];
	max = Max[comp["Count"]];
	If[max>8*8,AppendTo[data,{start,max}];];
	];
,{i,1,100}]
data



